### ISSUE TITLE
Missing Fatal/f, Panic/f

### ISSUE THREAD

**Issue by rantav** [InVisionApp/go-logger#6]
Hi, how open are you guys to adding support for `Fatal` and `Fatalf`?
Likewise for `Panic` and `Panicf`?

I'm happy to send a pull request.

**Comment by rantav** [comment]
Let me know what you think https://github.com/InVisionApp/go-logger/pull/7

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
